Wiki issue 62
aau-giraf/wiki pull request #100
Opened 2019-05-16 11:57 UTC by Jacob6565

This closes #62.

2019-05-17 07:17 UTC, Jacob6565 commented
@aau-giraf/sw608f19 you have been assigned this. Here's your checklist. I marked @swuf as the reviewer, but you might change it as you like.
Please use the following checklist:
- [ ] Is there documented which BLoCs/Screens the current class is related to?

- [ ] Is the responsibility/functionality of the current class explained? Also regarding the classes it is related to?

- [ ] If any unusual decisions are introduced in the code are they reasoned about in the documentation?

2019-05-17 07:56 UTC, swuf requested changes

2019-05-17 07:56 UTC, swuf commented on file_documentation/weekplanner/widgets/giraf_app_bar_widget.md
> +![Layout of Giraf app bar](../pictures/GirafAppbar.PNG)
Image doesn't seem to work. Maybe it's the .PNG with capital letters.

2019-05-17 07:56 UTC, swuf commented on file_documentation/weekplanner/widgets/giraf_app_bar_widget.md
> +This widget is the appbar at the top of many screens in the weekplanner application. The displayed icons are chosen dynamically and depends on the current screen and user mode. The icons as well as t
```suggestion
This widget is the app bar at the top of many screens in the weekplanner application. The displayed icons are chosen dynamically and depend on the current screen and user mode. The icons as well as their functionality are provided by `toolbar_bloc.dart`. 
```

2019-05-17 07:56 UTC, swuf commented on file_documentation/weekplanner/widgets/giraf_app_bar_widget.md
> +The appbar can contain many different buttons. To name a few: settings, logout, change to guardian, and change to citizen, all the icons can bee seen in `toolbar_bloc.dart`.
```suggestion
The app bar can contain many different buttons. To name a few: settings, logout, change to guardian, and change to citizen. All the icons can be seen in `toolbar_bloc.dart`.
```

2019-05-17 07:56 UTC, swuf commented on file_documentation/weekplanner/widgets/giraf_app_bar_widget.md
> +Giraf appbar is a stateless widget, thus it contains the build function which "describes" how the appbar should look:
```suggestion
Giraf app bar is a stateless widget, thus it contains the build function which "describes" how the app bar should look:
```

2019-05-17 07:56 UTC, swuf commented on file_documentation/weekplanner/widgets/giraf_app_bar_widget.md
> +The Giraf appbar consists of an appbar with buttons which are emitted from the stream called `toolbarBloc.visibleButtons`. That stream is populated with buttons by the method `toolbarBloc.updateIcons
```suggestion
The Giraf app bar consists of an app bar with buttons which are emitted from the stream called `toolbarBloc.visibleButtons`. That stream is populated with buttons by the method `toolbarBloc.updateIcons` which is the reason it is called as the first method.
```

2019-05-21 07:40 UTC, swuf approved these changes
Nice 🐤

2020-02-26 12:49 UTC, merged