Wiki issue 134
aau-giraf/wiki pull request #136
Opened 2020-03-06 13:11 UTC by Lortemanden

fixes #134 
Have documented the sprint planning method agreed upon between the PO and process group for sprint 1. Sprint intro is moved to the bottom with a comment about having been in used last year.

2020-03-09 11:51 UTC, Jakobzs requested changes

2020-03-09 11:51 UTC, Seraph2 commented on process_manual/project_meetings.md
> +The metting is then over and the representative meets with his group and does the following:
"meeting"

2020-03-09 11:51 UTC, Seraph2 commented on process_manual/project_meetings.md
> +2. Do a time estimate of the issues(Planning poker could be a way of doing it)
Make a space near the parenthese

2020-03-09 11:51 UTC, Seraph2 commented on process_manual/project_meetings.md
> +	-It's better to have few issues then to many for a sprint, since it's always possible to get new issues by contacting the PO group
Space at hyphen

2020-03-09 12:21 UTC, EsbenNedergaard commented on process_manual/project_meetings.md
> +3. The teams gather and quickly runs through the issues and sub-issues
should probably be 4. not 3. again

2020-03-09 12:23 UTC, EsbenNedergaard commented on process_manual/project_meetings.md
> +All following sprint intros will probably be shorter meetings, lasting no more than xx - xx minutes.
you write "sprint intros" i thought we called it "sprint plannings", also maybe not write xx-xx

2020-03-09 12:28 UTC, EsbenNedergaard commented on process_manual/project_meetings.md
> +## Sprint intro
I fell like this is kind of unnecessary and just confusing, because we no longer use it, either move it to another file or something

2020-03-09 12:29 UTC, Simkortet commented on process_manual/project_meetings.md
> +	-It's better to have few issues then to many for a sprint, since it's always possible to get new issues by contacting the PO group
"then" -> "than"

2020-03-09 12:30 UTC, EsbenNedergaard requested changes
Please check the comments for feedback

2020-03-09 12:30 UTC, Simkortet reviewed
Check spelling

2020-03-11 09:47 UTC, EsbenNedergaard approved these changes

2020-03-11 09:48 UTC, Simkortet approved these changes

2020-03-11 11:27 UTC, DumbLol approved these changes
missing "." in linje 28

2020-03-11 11:36 UTC, Jakobzs approved these changes

2020-03-17 11:48 UTC, mathiasandresen reviewed
deleted

2020-03-17 11:48 UTC, mathiasandresen reviewed
deleted

2020-03-30 11:37 UTC, closed without merging