Feature 123 - Restructured the wiki, and setup GH Pages using Mkdocs
aau-giraf/wiki pull request #146
Opened 2020-03-18 15:57 UTC by mathiasandresen

closing #4 and closing #123 

* Github Actions script setup to deploy the page.
* Restructed the wiki into categories
* Fixed broken links, wrong formatting

2020-03-18 16:22 UTC, MrPekar98 commented on docs/development/rest_api_development/ModelsAndDTOs.md
> +There should be an image here, but ```./images/preview-database.png``` does not exist.
Is the image important? Because, otherwise, I think it's better to just delete the sentence.

2020-03-18 17:01 UTC, MrPekar98 submitted a review, later dismissed

2020-03-19 12:48 UTC, Lortemanden requested changes
It looks good overall and the wiki is more intuitiv to read. There is though the front page which is called wiki. It has some links to different files but it seems random and out of touch with the main way to navigate the wiki. Could the front page instead point to "Getting Started", "Development", "Process Manuel" and "Releases"?

2020-03-23 10:34 UTC, MrPekar98 approved these changes

2020-03-23 11:43 UTC, Lortemanden approved these changes

2020-03-23 11:44 UTC, merged