Project management
aau-giraf/wiki pull request #15
Opened 2019-02-24 08:52 UTC by TobiasPalludan

2019-02-24 14:46 UTC, Bjerkk approved these changes

2019-02-24 17:25 UTC, KVISDAOWNER requested changes

2019-02-24 17:25 UTC, KVISDAOWNER commented on process_manual/code_workflow.md
> +entire documentation is seen in [the GitHub guides](https://help.github.com/en/articles/creating-issue-templates-for-your-repository). We **highly recommend** that
This is not the link that with the explanation of gitflow, it is instead a link for creating issue templates is cited which seems to be a mistake.

Correct gitflow link: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

2019-02-24 17:25 UTC, KVISDAOWNER commented on process_manual/organization_overview.md
> +
These first couples of lines don't seem necessary.

2019-02-24 19:42 UTC, KVISDAOWNER approved these changes

2019-02-25 07:35 UTC, merged

2019-02-26 07:52 UTC, TobiasPalludan commented
Solves #3