Wiki issue 155
aau-giraf/wiki pull request #176
Opened 2020-04-07 09:52 UTC by aerlin17

2020-04-07 13:29 UTC, melanieselman submitted a review, later dismissed

2020-04-07 13:48 UTC, giano574 requested changes
Generally fine

2020-04-07 13:48 UTC, giano574 commented on docs/development/Offline_mode.md
> +1. Citizens table is offline.
```suggestion
1. Citizen's tablet is offline.   
```

2020-04-07 13:48 UTC, giano574 commented on docs/development/Offline_mode.md
> +2. Guardians logs in and changes the citizens settings.
```suggestion
2. A guardian logs in on the same (offline) tablet and changes the citizen's settings.
```

2020-04-07 13:48 UTC, giano574 commented on docs/development/Offline_mode.md
> +4. The citizens device gets internet connection and now the changes has to be synced with the database. But now the guardian is not logged in anymore and the citizen do not have the permission to upd
```suggestion
4. The citizen's device gets internet connection and now the changes has to be synced with the database. But the guardian is not logged in anymore and the citizen does not have permission to update their changes through the web-api.

```

2020-04-07 13:48 UTC, giano574 commented on docs/development/Offline_mode.md
> +Possible solution would be to give a citizen more permissions in the wep-api to make changes
```suggestion
A possible solution would be to give a citizen permissions in the wep-api to make changes.

```

2020-04-07 13:48 UTC, giano574 commented on docs/development/Offline_mode.md
> +![image](https://cdn.discordapp.com/attachments/674940529124966402/691622267402190858/unknown.png)
The image is a little misleading; When the memory cache and local database can't respond to a query, and the REST API returns an answer, the path back to the bloc from the model adapter (in the lower right corner) is unclear. This was mentioned in the feedback by group 15.

2020-04-08 12:48 UTC, giano574 approved these changes

2020-04-09 07:16 UTC, melanieselman approved these changes

2020-04-09 14:13 UTC, merged