Feature 188
aau-giraf/wiki pull request #212
Opened 2020-05-11 08:53 UTC by jbjarn17

Fixes #188

2020-05-11 09:13 UTC, mads-bo reviewed
@aau-giraf/sw613f20 you have been assigned this. Here's your checklist.

Please use the following checklist:

**Code Documentation Only**

- [ ] It is documented which BLoCs/Screens the current class is related to
- [ ] The responsibility/functionality of the current class is explained. Also regarding the classes it is related to
- [ ] If any unusual decisions are introduced in the code, they reasoned about in the documentation
 
**Wiki Related**

- [ ] There are no dead links or references
- [ ] The markdown renders correctly in MkDocs
- [ ] The content is placed in the correct page/folder/section

You can run MkDocs locally by following [this guide](https://aau-giraf.github.io/wiki/writing_wiki/#running-locally)

2020-05-11 09:13 UTC, mads-bo reviewed
@aau-giraf/sw614f20 you have been assigned this. Here's your checklist.

Please use the following checklist:

**Code Documentation Only**

- [ ] It is documented which BLoCs/Screens the current class is related to
- [ ] The responsibility/functionality of the current class is explained. Also regarding the classes it is related to
- [ ] If any unusual decisions are introduced in the code, they reasoned about in the documentation
 
**Wiki Related**

- [ ] There are no dead links or references
- [ ] The markdown renders correctly in MkDocs
- [ ] The content is placed in the correct page/folder/section

You can run MkDocs locally by following [this guide](https://aau-giraf.github.io/wiki/writing_wiki/#running-locally)

2020-05-11 09:21 UTC, Lortemanden requested changes

2020-05-11 09:21 UTC, Lortemanden commented on docs/development/rest_api_development/EndpointsAndControllersTutorial.md
> +Typically, you would only want to use `[Authorize]` for the controller as specifying the role prevents you from specifying that some endpoints can only be used specific roles.
What are you trying to say here? I think that the sentence structure could use some work

2020-05-11 09:42 UTC, Lortemanden approved these changes

2020-05-12 07:26 UTC, Simon97 approved these changes

2020-05-12 07:28 UTC, merged