Documented login screen and added pictures
aau-giraf/wiki pull request #65
Opened 2019-05-03 08:08 UTC by Sworgon

2019-05-06 11:10 UTC, Jacob6565 commented
@aau-giraf/sw610f19 you have been assigned this. Here's your checklist. I marked @Moesgaarda as the reviewer, but you might change it as you like.
Please use the following checklist:
- [ ] Is there documented which BLoCs/Screens the current class is related to?

- [ ] Is the responsibility/functionality of the current class explained? Also regarding the classes it is related to?

- [ ] If any unusual decisions are introduced in the code are they reasoned about in the documentation?

Note: If you have any suggestions to what we can change, do not hesitate to contact us :D

2019-05-06 11:38 UTC, Tekrus requested changes

2019-05-06 11:38 UTC, Moesgaarda commented on file_documentation/weekplanner/screens/login_screen.md
> +The purple square marks the auto-login button.
```suggestion
The purple square marks the auto-login button and is only visible in debug mode.
```

2019-05-06 11:38 UTC, Moesgaarda commented on file_documentation/weekplanner/screens/login_screen.md
> +## Button
Auto-login button?

2019-05-06 18:23 UTC, Sworgon commented on file_documentation/weekplanner/screens/login_screen.md
> +## Button
yes

2019-05-07 08:31 UTC, Tekrus approved these changes

2019-05-07 10:39 UTC, merged