Bloc pattern
aau-giraf/wiki pull request #85
Opened 2019-05-09 13:03 UTC by Hylet

This closes #84.
This is written by @aau-giraf/sw611f19 and edited by @aau-giraf/sw608f19.

2019-05-09 17:16 UTC, Moesgaarda commented
I'd like @sipman to be one of the reviewers to ensure that he feels that this still represents the essentials of his original version

2019-05-10 08:25 UTC, Bjerkk commented
@aau-giraf/sw611f19  you have been assigned this. Here's your checklist. I marked @sipman  as the reviewer, but you might change it as you like.
Please use the following checklist:
- [ ] Is there documented which BLoCs/Screens the current class is related to?

- [ ] Is the responsibility/functionality of the current class explained? Also regarding the classes it is related to?

- [ ] If any unusual decisions are introduced in the code are they reasoned about in the documentation?

Note: If you have any suggestions to what we can change, do not hesitate to contact us :D

2019-05-10 09:50 UTC, sipman commented
@Bjerkk I will do the review, but your check list do not apply to this review :)

2019-05-10 10:01 UTC, sipman requested changes

2019-05-10 10:01 UTC, sipman commented on tutorials/bloc_pattern/BLoCPattern.md
> +The BLoC pattern is a pattern that aims to isolate all business logic from UI code in order to be able to re-use the business logic [6]. The business logic has to be platform independent, meaning usa
Not on the web-application and mobile as in only those. That is jsut the example set by google.

The pattern states that it use be useable on all platform.. So also desktop, embedded, what ever platform.

2019-05-10 10:01 UTC, sipman commented on tutorials/bloc_pattern/BLoCPattern.md
> +To understand the BLoC pattern one first needs to understand what a BLoC is. A BLoC is a simple class that only takes sinks as input and exposes streams as output [6]. All business logic should be in
```suggestion
To understand the BLoC pattern one first needs to understand what a BLoC is. A BLoC is a simple class that only takes sinks as input and exposes streams as output [6]. All business logic should be inside a BLoC. The intuition is that BLoCs are the building blocks of the application [6]. Another key requirement of a BLoC is that all dependencies should be injected [6], so if an API is needed it should be injected in the constructor of the BLoC. This allows the web-platform to use a JSON-API and the mobile-platform to use a BINARY-API and other similar situations, while all platforms still uses the same BLoC without any modifications. An application thereby consist of many BLoCs with different responsibilities. The BLoC can then be used by the UI components of all platforms.
```

2019-05-10 10:01 UTC, sipman commented on tutorials/bloc_pattern/BLoCPattern.md
> +* Start by creating a BLoC per UI Screen, then after implementing the functionality consider to refactor to shared BLoC
```suggestion
* Start by creating a BLoC per UI Screen, then after implementing the functionality consider to refactor to shared BLoCs
```

2019-05-10 10:37 UTC, Hylet commented on tutorials/bloc_pattern/BLoCPattern.md
> +The BLoC pattern is a pattern that aims to isolate all business logic from UI code in order to be able to re-use the business logic [6]. The business logic has to be platform independent, meaning usa
Changed the examples to a more generic example

2019-05-10 13:12 UTC, sipman approved these changes

2019-05-11 13:26 UTC, merged